### PR TITLE
Add appliedwork api

### PR DESCRIPTION
**Pull request by qiujian16**

### CODE REVIEW

**Comment by RainbowMango** [comment]
LGTM.
/assign @pmorie

**Comment by RainbowMango** [comment]
I wonder if we should talk about the `AppliedWork` API somewhere, such as the KEP?

**Comment by qiujian16** [comment]
Do you think we should add  it in  the doc? It might relates to the detailed implementation, but not a user interfacing  API.

**Comment by mikeshng** [comment]
/remove-lifecycle stale

I am working on the enhancement proposal for this PR. Sorry it's been taking so long.

**Comment by RainbowMango** [comment]
Thanks @mikeshng, could you please cc me when the proposal is ready for review?

**Pull request closed without merging**
